version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "direct"
