name: Autopublish

on:
    push:
        branches:
            - main

jobs:
    autopublish:
        name: Publish release if package.json version was bumped
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Check package version
              id: cpv
              uses: PostHog/check-package-version@v2

            - name: Echo versions
              run: |
                  echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
                  echo "Published version: ${{ steps.cpv.outputs.published-version }}"

            - name: Install dependencies
              if: steps.cpv.outputs.is-new-version == 'true'
              run: npm ci

            - name: Publish new version
              if: steps.cpv.outputs.is-new-version == 'true'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
