name: Auto-comment on PR
on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Gather PR details
      id: pr_details
      run: |
        set -e  # Stop execution on any error
        
        PR_ID=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH") || exit 1
        PR_AUTHOR=$(jq -r ".pull_request.user.login" "$GITHUB_EVENT_PATH") || exit 1
        PR_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH") || exit 1
    
        REPO_URL="https://github.com/${{ github.repository }}/blob/$PR_BRANCH"
        
        FILES_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID/files) || exit 1
    
        FILES_LINKED=()
        
        for row in $(echo "${FILES_JSON}" | jq -r '.[] | @base64'); do
          _jq() {
            echo ${row} | base64 --decode | jq -r ${1}
          }
          
          FILE_NAME=$(_jq '.filename')
          ADDITIONS=$(_jq '.additions')
          DELETIONS=$(_jq '.deletions')
          CHANGES=$(_jq '.changes')
          
          FILES_LINKED+=("- [$FILE_NAME]($REPO_URL/$FILE_NAME) (Additions: $ADDITIONS, Deletions: $DELETIONS, Changes: $CHANGES)")
        done

        FINAL_FILES_LINKED=$(IFS=$'\n'; echo "${FILES_LINKED[*]}")
        
        # Store this in a file instead of an environment variable
        echo "$FINAL_FILES_LINKED" > /tmp/final_files_linked.txt

        echo "PR_ID=$PR_ID" >> $GITHUB_ENV
        echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

    - name: Set Workflow Status
      run: echo "WORKFLOW_STATUS=success" >> $GITHUB_ENV
      if: success()

    - name: Error Handling
      if: failure()
      run: |
        echo "WORKFLOW_STATUS=failure" >> $GITHUB_ENV
        echo "An error occurred. Check the logs for details."

    - name: Add comment to PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message_file: /tmp/final_files_linked.txt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
